### PR TITLE
add something and fix some bug

### PR DESCRIPTION
**Pull request by dayfox5317**
1.Add " delete line "  function
2.Add some Signal event about line  
3.Add Group Node (Bad effect ,Suggest to skip)
4.Fix some bug

### CODE REVIEW

**Comment by dayfox5317** [comment]
![https://github.com/zeusgame1/UnityRuntimeNodeEditor/blob/master/quickview.gif]

**Comment by dayfox5317** [comment]
quickview

**Comment by cemuka** [comment]
Hi @dayfox5317! Thanks for new additions, I'll merge it asap. 

btw, I didn't get "Bad effect ,Suggest to skip" here? You mean you didn't like it?

**Comment by cemuka** [comment]
I was thinking about creating an issue to seek help though. You know how unity handles `ContexMenu`and `MenuItem`. You could create a nested context menu item like this `MenuItem("Menu/Child1/Child2")` like so. I tried to implement it but I couldn't simple way yo do it. I'm not sure how their implementation works.

**Comment by dayfox5317** [comment]
> I was thinking about creating an issue to seek help though. You know how unity handles `ContexMenu`and `MenuItem`. You could create a nested context menu item like this `MenuItem("Menu/Child1/Child2")` like so. I tried to implement it but I couldn't simple way yo do it. I'm not sure how their implementation works.

i have add it,But I can not guarantee if it works 
quickview2

**Comment by dayfox5317** [comment]
> Hi @dayfox5317! Thanks for new additions, I'll merge it asap.
> 
> btw, I didn't get "Bad effect ,Suggest to skip" here? You mean you didn't like it?

Coupling and bad  Code  in "Group Node" , don't merge it ...

**Comment by cemuka** [comment]
Super cool 😎. I think it looks working but I'll give it a shot. I'll merge it all and try to refactor the node group. If I could fit in, I think it would be a good feature to add. 

Please let me know about how we could improve further this project.

**Pull request merged**
